name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            
          color_snake: "#6E45E2"        
          color_dots: "#24292e,#1B1F23,#8B949E,#6E45E2,#7F54EC" 
          
          grid_layout: compact    
          grid_size: 15        
          grid_area: 80x20      
          
          speed: 5             
          animation_length: 4   
          
          svg_out_path: dist/snake.svg
          svg_out_path_dark: dist/snake-dark.svg

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
